version: "2"
services:
  nacos:
    container_name: nacos-mysql8
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=${host_ip}
      - MYSQL_MASTER_SERVICE_PORT=${host_port}
      - MYSQL_SERVICE_USER=${user}
      - MYSQL_SERVICE_PASSWORD=${password}
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - JVM_XMS=512m
      - JVM_MMS=512m
    image: nacos/nacos-server:1.3.1
    ports:
      - "8848:8848"
      - "9555:9555"
    volumes:
      - "./init.d/custom.properties:/home/nacos/init.d/custom.properties"
      - "./nacos-logs:/home/nacos/logs"

